### ISSUE TITLE
Settings window doesn't shrink

### ISSUE THREAD

**Issue by Tichy** [aleixq/apptitle-plasmoid#2]
Open the plasmoid's settings, enlarge the window, then shrink it. The gap between elements doesn't shrink. See screen capture: https://imgur.com/a/UhAwX

**Comment by aleixq** [comment]
Thank's, I'l take a look asap (by now it's later than soon...). But PR's are welcome

**Comment by aleixq** [comment]
Sorry to bother you but due to recent github changes I moved the source code to gitlab. If still interessed, the issue has been moved to https://gitlab.com/aleixq/apptitle-plasmoid/issues/2. This way it will be obtained automatically from upstream in store.kde.org. I'll close the issues in github as soon as possible.
